version: '3.8'

services:
  tensurf-ui:
    container_name: hub-tensurf-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: always

  tensurf-daphne:
    container_name: hub-tensurf-daphne
    build:
      context: ./api
      dockerfile: Dockerfile.daphne
    env_file:
      - .env
    depends_on:
      - tensurf-postgres
      - tensurf-redis
      - tensurf-minio
    volumes:
      - /var/run/daphne:/var/run/daphne

  tensurf-gunicorn:
    container_name: hub-tensurf-gunicorn
    build:
      context: ./api
      dockerfile: Dockerfile.gunicorn
    env_file:
      - .env
    depends_on:
      - tensurf-postgres
      - tensurf-redis
      - tensurf-minio
    # ports:
    #   - 8000:8001
    volumes:
      - ./api/static:/app/static

  tensurf-postgres:
    container_name: hub-tensurf-postgres
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    restart: always

  tensurf-pgadmin:
    container_name: hub-tensurf-pgadmin
    image: dpage/pgadmin4:6.1
    environment:
      PGADMIN_DEFAULT_EMAIL: tensurf@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tensurf
    ports:
      - "5050:80"
    volumes:
      - tensurf_pgdata:/var/lib/pgadmin
    restart: always

  tensurf-redis:
    container_name: hub-tensurf-redis
    image: "redis:alpine"
    environment:
      REDIS_DB: ${REDIS_DB}
    restart: always

  tensurf-minio:
    container_name: hub-tensurf-minio
    image: minio/minio
    hostname: "minio"
    volumes:
      - /mnt/hub-tensurf-minio:/data
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY}
      MINIO_SECRET_KEY: ${AWS_SECRET_KEY}
    command: 'minio server /data --console-address ":9001"'
    ports:
      - 9001:9001

#  minio-client:
#    image: minio/mc
#    depends_on:
#      - tensurf-minio
#    entrypoint: >
#      /bin/sh -c "
#      /usr/bin/mc config host rm expo;
#      /usr/bin/mc config host add --quiet --api s3v4 tensurf http://tensurf-minio:9000 tensurf tensurf-hub;
#      /usr/bin/mc rb --force tensurf/chatbot/;
#      /usr/bin/mc mb --quiet tensurf/chatbot/;
#      /usr/bin/mc policy set public tensurf/chatbot;
#      "

networks:
  default:
    external: true
    name: tensurf-network

volumes:
  postgres_data:
  tensurf_pgdata:
