version: "3"

services:
  tensurf-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: always
  
  tensurf-daphne:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: daphne -u /var/run/daphne/daphne.sock tensurf.asgi:application
    env_file:
      - .env
    depends_on:
      - tensurf-postgres
      - tensurf-redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  tensurf-gunicorn:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: gunicorn --workers=${NPROC} --bind 0.0.0.0:8001 tensurf.wsgi:application
    env_file:
      - .env
    depends_on:
      - tensurf-postgres
      - tensurf-redis
    volumes:
      - .:/app
    ports:
      - "8001:8001"

  tensurf-postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  tensurf-pgadmin:
    image: dpage/pgadmin4:6.1
    environment:
      PGADMIN_DEFAULT_EMAIL: tensurf@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tensurf
    ports:
      - "5050:80"
    volumes:
      - tensurf_pgdata:/var/lib/pgadmin
    restart: always

  tensurf-redis:
    image: "redis:alpine"
    environment:
      REDIS_DB: ${REDIS_DB}
    restart: always

networks:
  default:
    external: true
    name: tensurf-network

volumes:
  postgres_data:
  tensurf_pgdata:
