version: "3"

services:
  tensurf-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    env_file:
      - .ui.env
    restart: always

  tensurf-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .api.env
    depends_on:
      - tensurf-postgres
      - tensurf-redis
    restart: always

  tensurf-postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file:
      - .api.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  tensurf-redis:
    image: "redis:alpine"
    env_file:
      - .api.env
    environment:
      REDIS_DB: ${REDIS_DB}
    restart: always

networks:
  default:
    external: true
    name: tensurf-network

volumes:
  postgres_data:

    


