version: '3.8'

services:
  hub-tensurf-ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: always
    environment:
      - NEXT_PUBLIC_TENSURF_URL=https://tensurf.ai

  hub-tensurf-gunicorn:
    build:
      context: ./api
      dockerfile: Dockerfile.gunicorn
    env_file:
      - .env
    depends_on:
      - hub-tensurf-postgres
      - hub-tensurf-redis
      - hub-tensurf-minio
    volumes:
      - /var/run/gunicorn:/var/run/gunicorn
    command: >
      sh -c "python manage.py migrate && gunicorn api.wsgi:application --bind 0.0.0.0:8000"

  hub-tensurf-postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    restart: always

  hub-tensurf-redis:
    image: redis:latest
    container_name: hub-tensurf-redis
    ports:
      - 6379:6379

  hub-tensurf-minio:
    image: minio/minio
    container_name: hub-tensurf-minio
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
    command: server /data

volumes:
  postgres_data:
  minio_data:

